packages:
  - packages/*

catalog:
  "lexical": "0.36.2"
  "@lexical/clipboard": "0.36.2"
  "@lexical/code": "0.36.2"
  "@lexical/code-shiki": "0.36.2"
  "@lexical/dragon": "0.36.2"
  "@lexical/file": "0.36.2"
  "@lexical/hashtag": "0.36.2"
  "@lexical/history": "0.36.2"
  "@lexical/html": "0.36.2"
  "@lexical/link": "0.36.2"
  "@lexical/list": "0.36.2"
  "@lexical/mark": "0.36.2"
  "@lexical/markdown": "0.36.2"
  "@lexical/overflow": "0.36.2"
  "@lexical/plain-text": "0.36.2"
  "@lexical/rich-text": "0.36.2"
  "@lexical/selection": "0.36.2"
  "@lexical/table": "0.36.2"
  "@lexical/text": "0.36.2"
  "@lexical/utils": "0.36.2"
  "@lexical/yjs": "0.36.2"
  "tiny-invariant": "^1.3.3"
  "vue": "^3.5.17"
  "yjs": "^13.6.18"